### ISSUE TITLE
No eventname EmergencyAccessToken for AWS CloudTrail

### ISSUE THREAD

**Issue by manohnz** [ep3p/Sentinel_KQL#1]
Hi there

I used your the below KQL for my work.

AWSCloudTrail
| where EventName contains "EmergencyAccessToken" //EventName == "AdminGetEmergencyAccessToken"
| project
    TimeGenerated,
    UserIdentityAccountId,
    UserIdentityUserName,
    UserIdentityArn,

I later found that there is no such event name available in AWS CloudTrail. https://www.gorillastack.com/blog/real-time-events/cloudtrail-event-names/#direct-connect-cloudtrail.

If EmergencyAccessToken is available, can you please let me know how to create this event in AWS?

Thanks
Manohar

**Comment by ep3p** [comment]
Hi @manohnz ,

I am just starting to work with AWS logs, you are right, I also did not find the event "AdminGetEmergencyAccessToken" in any AWS documentation when I encountered this event. And unfortunately I didn't know how peculiar this event would be, otherwise I would have exported this log. I think there are other "AdminGet*" events.

I can tell you the complete EventName was ```EventName == "AdminGetEmergencyAccessToken"```. I have only found this event once, when I was looking at all the distinct EventName I had available, with:

```
AWSCloudTrail
| distinct EventName
```

This event was a failure (it had a specific column with an error), and I believe a theat actor tried to take over an account, unsuccessfully.

I also believe you don't need to create a specific configuration for this event to be received, the default AWS connector and the default configuration for AWSCloudTrail should be enough. BUT I do not know the specific EventSource of this event (sorry), and maybe setting up Emergency Access in AWS is not so common (https://docs.aws.amazon.com/singlesignon/latest/userguide/emergency-access.html).

Let me know if you have any more questions, if not maybe I could close this issue.

**Comment by manohnz** [comment]
Hey Jose

Makes sense. Please feel free to close it. Thanks.

Cheers
Manohar
